@startuml
class User {
    -name
    -email
}

class UserResource {
    +getAll(): User[]
    +getById(id: int) User
    +add(user: User)
}

interface UserService {
    +addUser(user: User)
    +getAllUsers(): User[]
    +getUserById(id: int): User
}

class UserServiceDefault {
     +addUser(user: User)
     +getAllUsers(): User[]
     +getUserById(id: int): User
}

UserResource *-- UserService
UserServiceDefault ..> UserService

@enduml